openapi: 3.0.3
info:
  title: Title
  description: Title
  version: 1.0.0
servers:
  - url: 'http://127.0.0.1:5000'
paths:
  /llm/query:
    post:
      summary: Process a request with query and func_on
      description: This API processes a POST request that includes a query and func_on field.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: string
                  description: The query to be processed
                  example: "SELECT * FROM users"
                func_on:
                  type: string
                  description: The function or action to be executed on the query
                  example: "execute"
              required:
                - query
                - func_on
      responses:
        200:
          description: Successfully processed the request
          content:
            application/json:
              schema:
                type: object
                properties:
                  content:
                    type: string
                    description: The result or output of the processing
                    example: "Query executed successfully"
                  status:
                    type: string
                    description: The status of the operation
                    example: "success"
        400:
          description: Invalid input, missing required fields or invalid format
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message describing the invalid request
                    example: "Missing required fields"
        500:
          description: Internal server error, something went wrong during processing
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message describing the internal server issue
                    example: "Database connection failed"
